import { getProductOrderWhatsAppUrl } from "@/lib/whatsapp";

export interface Product {
  id: number;
  name: string;
  brand: string;
  price: number;
  oldPrice?: number;
  image: string;
  category: string;
  isNew?: boolean;
  isLimited?: boolean;
  description: string;
  material: string;
  size: string;
  color: string;
  careInstructions: string;
}

const CARE_SILK =
  "Kuru temizleme önerilir. Elde yıkama yapılacaksa ilk soğuk suyla nazikçe yıkayın. Ters çevirip düşük ısıda ütüleyin. Doğrudan güneş ışığında kurutmayın.";
const CARE_COTTON = "30 derecede yıkanabilir. Gölgede kurutun. Orta ısıda ütüleyin.";

function p(file: string) {
  return `/products/${file}`;
}

export const allProducts: Product[] = [
  // ==================== VAKKO ====================
  { id: 1, name: "Vakko Twill İpek Esarp - Kareli Buz Mavisi", brand: "Vakko", price: 2290, image: p("esarp-030.jpeg"), category: "geometrik", description: "Vakko buz mavisi zemin üzerinde sulu boya fırça darbeleriyle kare desen twill ipek esarp. Minimalist ve modern.", material: "%100 İpek Twill", size: "90x90 cm", color: "Buz Mavisi-Lacivert", careInstructions: CARE_SILK },
  { id: 2, name: "Vakko Twill İpek Esarp - Paisley Siyah Toprak", brand: "Vakko", price: 2790, oldPrice: 3490, image: p("esarp-031.jpeg"), category: "desenli", isNew: true, description: "Vakko siyah zemin üzerinde kırmızı, turuncu ve altın paisley desenleri. Zengin dokusu ve detaylı motifleriyle premium bir parça.", material: "%100 İpek Twill", size: "90x90 cm", color: "Siyah-Kırmızı-Turuncu", careInstructions: CARE_SILK },
  { id: 3, name: "Vakko Twill İpek Esarp - Osmanlı Motif Lacivert", brand: "Vakko", price: 2990, image: p("esarp-032.jpeg"), category: "ipek-esarp", description: "Vakko lacivert zemin üzerinde turkuaz Osmanlı motifleri twill ipek esarp. İnci ve mücevher detaylarıyla görkemli bir tasarım.", material: "%100 İpek Twill", size: "90x90 cm", color: "Lacivert-Turkuaz", careInstructions: CARE_SILK },
  { id: 4, name: "Vakko Twill İpek Esarp - Çiçekli Hardal-Kahve", brand: "Vakko", price: 2590, oldPrice: 3090, image: p("esarp-034.jpeg"), category: "desenli", isNew: true, description: "Vakko hardal ve kahverengi zemin üzerinde beyaz çiçek motifleri twill ipek esarp. Mavi bordür ile doğadan ilham alan sonbahar tasarımı.", material: "%100 İpek Twill", size: "90x90 cm", color: "Hardal-Kahve", careInstructions: CARE_SILK },
  { id: 5, name: "Vakko Twill İpek Esarp - Chevron Siyah-Gri", brand: "Vakko", price: 2490, image: p("esarp-035.jpeg"), category: "geometrik", description: "Vakko siyah ve gri tonlarında chevron (ok ucu) geometrik desenli twill ipek esarp. Monokrom şıklığın temsilcisi.", material: "%100 İpek Twill", size: "90x90 cm", color: "Siyah-Gri-Beyaz", careInstructions: CARE_SILK },
  { id: 6, name: "Vakko Twill İpek Esarp - Çizgili Siyah-Beyaz Mini", brand: "Vakko", price: 1990, image: p("esarp-036.jpeg"), category: "geometrik", description: "Vakko siyah-beyaz dalga çizgili twill ipek esarp. Pembe bordür detayiyla minimalist ve modern. Kompakt boyutuyla her kombine uyumlu.", material: "%100 İpek Twill", size: "70x70 cm", color: "Siyah-Beyaz-Pembe", careInstructions: CARE_SILK },
  { id: 7, name: "Vakko Twill İpek Esarp - Pudra Gül Buketi", brand: "Vakko", price: 2390, oldPrice: 2890, image: p("esarp-037.jpeg"), category: "desenli", isNew: true, description: "Vakko pudra ve somon tonlarında büyük gül buketi desenli twill ipek esarp. Vakko özel kırmızı çantasıyla sunulan premium parça.", material: "%100 İpek Twill", size: "90x90 cm", color: "Pudra-Somon", careInstructions: CARE_SILK },
  { id: 8, name: "Vakko Twill İpek Esarp - Geometrik Retro", brand: "Vakko", price: 2590, image: p("esarp-038.jpeg"), category: "geometrik", description: "Vakko retro geometrik desenli twill ipek esarp. Canlı renklerle 70'ler estetiğinden ilham alan cesur ve dikkat çekici tasarım.", material: "%100 İpek Twill", size: "90x90 cm", color: "Retro Çok Renkli", careInstructions: CARE_SILK },

  // ==================== BELLI ====================
  { id: 9, name: "Belli Twill İpek Esarp - Dalga Mavi", brand: "Belli", price: 1753, image: p("esarp-028.jpeg"), category: "ipek-esarp", isNew: true, description: "Belli lacivert zemin üzerinde beyaz dalga ve çiçek bordür desenli twill ipek esarp. Zarif dalga motifleri iç içe geçen katmanlar oluşturur.", material: "%100 İpek Twill", size: "90x90 cm", color: "Lacivert-Beyaz", careInstructions: CARE_SILK },
  { id: 10, name: "Belli Twill İpek Esarp - Vintage Gül Yeşil-Kahve", brand: "Belli", price: 1849, oldPrice: 2400, image: p("esarp-029.jpeg"), category: "desenli", description: "Belli koyu yeşil zemin üzerinde vintage gül buketi desenli twill ipek esarp. Kırmızı, pembe ve sari güller sulu boya efektinde.", material: "%100 İpek Twill", size: "90x90 cm", color: "Yeşil-Kırmızı-Pembe", careInstructions: CARE_SILK },

  // ==================== VISSONA ====================
  { id: 11, name: "Vissona Twill İpek Esarp - Soyut Şehir Gri", brand: "Vissona", price: 1449, image: p("esarp-060.jpeg"), category: "geometrik", description: "Vissona siyah ve gri tonlarında soyut şehir silüeti desenli twill ipek esarp. Modern çizgiler ve fırça darbeleriyle avangard.", material: "%100 İpek Twill", size: "90x90 cm", color: "Gri-Siyah-Beyaz", careInstructions: CARE_SILK },
  { id: 12, name: "Vissona Twill İpek Esarp - Soyut Şehir Mavi", brand: "Vissona", price: 1449, image: p("esarp-065.jpeg"), category: "ipek-esarp", isNew: true, description: "Vissona mavi ve bej tonlarında soyut şehir silüeti desenli twill ipek esarp. Aynı serinin mavi varyasyonu.", material: "%100 İpek Twill", size: "90x90 cm", color: "Mavi-Bej-Beyaz", careInstructions: CARE_SILK },
  { id: 13, name: "Vissona Twill İpek Esarp - Soyut Şehir Pembe-Mavi", brand: "Vissona", price: 1549, oldPrice: 1999, image: p("esarp-070.jpeg"), category: "geometrik", description: "Vissona pembe ve mavi tonlarında soyut şehir silüeti desenli twill ipek esarp. Canlı renk kombinasyonuyla göz alıcı.", material: "%100 İpek Twill", size: "90x90 cm", color: "Pembe-Mavi", careInstructions: CARE_SILK },
  { id: 14, name: "Vissona Twill İpek Esarp - Soyut Fusya-Mavi-Yeşil", brand: "Vissona", price: 1549, image: p("esarp-072.jpeg"), category: "geometrik", isNew: true, description: "Vissona fusya, mavi ve yeşil tonlarında soyut geometrik desenli twill ipek esarp. Model üzerinde gösterilen özel kombinleme stili.", material: "%100 İpek Twill", size: "90x90 cm", color: "Fusya-Mavi-Yeşil", careInstructions: CARE_SILK },
  { id: 15, name: "Vissona Twill İpek Esarp - Soyut Kahve Tipografi", brand: "Vissona", price: 1349, oldPrice: 1799, image: p("esarp-077.jpeg"), category: "geometrik", isNew: true, description: "Vissona %100 twill ipek esarp. Kahverengi tonlarında soyut harf ve tipografi motifleri. Fırça darbeleri efektiyle modern.", material: "%100 İpek Twill", size: "90x90 cm", color: "Kahve-Bej-Siyah", careInstructions: CARE_SILK },

  // ==================== ZERAFETIM ====================
  { id: 16, name: "Zerafetim Twill Esarp - Botanik Gri", brand: "Zerafetim", price: 2240, oldPrice: 2800, image: p("esarp-095.jpeg"), category: "desenli", description: "Zerafetim gri zemin üzerinde egrelti otu, kelebek ve çiçek motifleri. Botanik bahce ilhamli sanatsal tasarım.", material: "%100 İpek Twill", size: "90x90 cm", color: "Gri-Siyah-Beyaz", careInstructions: CARE_SILK },
  { id: 17, name: "Zerafetim Twill Esarp - Tropikal Mor-Pembe", brand: "Zerafetim", price: 2399, image: p("esarp-096.jpeg"), category: "desenli", isNew: true, description: "Zerafetim mor, pembe ve fusya dikey seritler üzerinde tropikal bitki cizimleri. Palmiye ve egzotik yaprak motifleriyle yaz koleksiyonu.", material: "%100 İpek Twill", size: "90x90 cm", color: "Mor-Pembe-Fusya", careInstructions: CARE_SILK },
  { id: 18, name: "Zerafetim Twill Esarp - Istanbul Sulu Boya", brand: "Zerafetim", price: 2599, oldPrice: 3200, image: p("esarp-097.jpeg"), category: "ipek-esarp", isLimited: true, description: "Zerafetim İstanbul silüeti sulu boya tarzında. Leopar bordürlu krem-pembe tonlarında cami ve kemer motifleriyle sınırlı üretim.", material: "%100 İpek Twill", size: "90x90 cm", color: "Krem-Pembe-Leopar", careInstructions: CARE_SILK },
  { id: 19, name: "Zerafetim Twill Esarp - Botanik Beyaz", brand: "Zerafetim", price: 2240, image: p("esarp-098.jpeg"), category: "desenli", description: "Zerafetim beyaz zemin üzerinde siyah egrelti otu, kelebek ve çiçek motifleri. Aynı botanik serinin beyaz varyasyonu.", material: "%100 İpek Twill", size: "90x90 cm", color: "Beyaz-Siyah", careInstructions: CARE_SILK },
  { id: 20, name: "Zerafetim Twill Esarp - Osmanlı Lacivert-Turuncu", brand: "Zerafetim", price: 2399, oldPrice: 2800, image: p("esarp-099.jpeg"), category: "ipek-esarp", isNew: true, description: "Zerafetim lacivert zemin üzerinde turuncu ve mavi Osmanlı motifleri. Beyaz örgü bordür detayiyla geleneksel ve modern sentez.", material: "%100 İpek Twill", size: "90x90 cm", color: "Lacivert-Turuncu-Mavi", careInstructions: CARE_SILK },
  { id: 21, name: "Zerafetim Twill Esarp - Geometrik Mavi-Siyah", brand: "Zerafetim", price: 2240, image: p("esarp-100.jpeg"), category: "geometrik", description: "Zerafetim siyah zemin üzerinde mavi geometrik dalga motifleri. Cesur ve modern grafik tasarım.", material: "%100 İpek Twill", size: "90x90 cm", color: "Mavi-Siyah-Beyaz", careInstructions: CARE_SILK },
  { id: 22, name: "Zerafetim Twill Esarp - Retro Çizgili Pudra", brand: "Zerafetim", price: 2399, image: p("esarp-101.jpeg"), category: "ipek-esarp", isNew: true, description: "Zerafetim pudra, kahve ve siyah dikey çizgiler. Güneş motifi ve çiçek bordürlu retro tasarım. Manken üzerinde gösterilen zarif parça.", material: "%100 İpek Twill", size: "90x90 cm", color: "Pudra-Kahve-Siyah", careInstructions: CARE_SILK },
  { id: 23, name: "Zerafetim Twill Esarp - Bahar Çiçekleri Siyah", brand: "Zerafetim", price: 2599, oldPrice: 3200, image: p("esarp-102.jpeg"), category: "desenli", isLimited: true, description: "Zerafetim siyah zemin üzerinde canlı pembe, mor, sari ve turuncu bahar çiçekleri. Sanatsal el boyama etkisinde sınırlı üretim.", material: "%100 İpek Twill", size: "90x90 cm", color: "Siyah-Çok Renkli", careInstructions: CARE_SILK },
  { id: 24, name: "Zerafetim Twill Esarp - Kazayagi Pembe-Gri", brand: "Zerafetim", price: 2240, image: p("esarp-103.jpeg"), category: "geometrik", description: "Zerafetim gri-beyaz kazayağı (houndstooth) deseni, pembe ve siyah bordür. Klasik ve modern sentezi.", material: "%100 İpek Twill", size: "90x90 cm", color: "Gri-Beyaz-Pembe", careInstructions: CARE_SILK },
  { id: 25, name: "Zerafetim Twill Esarp - Patchwork Pembe-Kazayagi", brand: "Zerafetim", price: 2399, oldPrice: 2800, image: p("esarp-104.jpeg"), category: "geometrik", isNew: true, description: "Zerafetim dört karelik patchwork tasarım. Pembe ekose ve gri kazayağı motifleri bir arada. Antrasit çerçeve detayi.", material: "%100 İpek Twill", size: "90x90 cm", color: "Pembe-Gri-Siyah", careInstructions: CARE_SILK },
  { id: 26, name: "Zerafetim Twill Esarp - Sakayik Siyah", brand: "Zerafetim", price: 2599, image: p("esarp-078.jpeg"), category: "desenli", isLimited: true, description: "Zerafetim siyah zemin üzerinde büyük pembe sakayik (peony) çiçekleri. Fotorealistik detaylarıyla göz alıcı sınırlı üretim.", material: "%100 İpek Twill", size: "90x90 cm", color: "Siyah-Pembe", careInstructions: CARE_SILK },
  { id: 27, name: "Zerafetim Twill Esarp - Zincir Yeşil-Turuncu", brand: "Zerafetim", price: 2399, oldPrice: 2800, image: p("esarp-079.jpeg"), category: "ipek-esarp", isNew: true, description: "Zerafetim koyu yeşil zemin üzerinde turuncu kemer ve zincir motifleri. Hermes ilhamli ekoseli desen detaylari.", material: "%100 İpek Twill", size: "90x90 cm", color: "Yeşil-Turuncu-Mavi", careInstructions: CARE_SILK },
  { id: 28, name: "Zerafetim Twill Esarp - Çiçek Sarı-Siyah", brand: "Zerafetim", price: 2240, image: p("esarp-080.jpeg"), category: "desenli", description: "Zerafetim krem zemin üzerinde sari çiçek yaprak motifleri, siyah şerit bordür. Enerjik ve ferah yaz tasarımı.", material: "%100 İpek Twill", size: "90x90 cm", color: "Sari-Siyah-Krem", careInstructions: CARE_SILK },
  { id: 29, name: "Zerafetim Jakarlı Sal - Lacivert Dama", brand: "Zerafetim", price: 1490, image: p("esarp-081.jpeg"), category: "sal", description: "Zerafetim lacivert jakarlı dama desenli sal. Tone-on-tone dokuma detaylarıyla minimalist ve şık.", material: "İpek-Pamuk Jakar", size: "70x200 cm", color: "Lacivert", careInstructions: CARE_SILK },
  { id: 30, name: "Zerafetim Jakarlı Sal - Bej Dama", brand: "Zerafetim", price: 1490, image: p("esarp-082.jpeg"), category: "sal", isNew: true, description: "Zerafetim bej-krem jakarlı dama desenli sal. Aynı serinin açık renk varyasyonu. Zarif ve doğal.", material: "İpek-Pamuk Jakar", size: "70x200 cm", color: "Bej-Krem", careInstructions: CARE_SILK },
  { id: 31, name: "Zerafetim Twill Esarp - Mini Puantiye Bordo", brand: "Zerafetim", price: 2240, image: p("esarp-083.jpeg"), category: "desenli", description: "Zerafetim bordo zemin üzerinde mini puantiye ve yıldız motifleri. Dikis bordür detaylı zarif tasarım.", material: "%100 İpek Twill", size: "90x90 cm", color: "Bordo-Beyaz", careInstructions: CARE_SILK },
  { id: 32, name: "Zerafetim Twill Esarp - Tren Pop Art Fusya", brand: "Zerafetim", price: 2599, oldPrice: 3200, image: p("esarp-084.jpeg"), category: "geometrik", isLimited: true, description: "Zerafetim fusya zemin üzerinde turuncu vintage tren ve ray motifi. Pop art tarzında cesur ve eğlenceli sınırlı üretim.", material: "%100 İpek Twill", size: "90x90 cm", color: "Fusya-Turuncu", careInstructions: CARE_SILK },
  { id: 33, name: "Zerafetim Twill Esarp - Tropikal Meyve Turuncu", brand: "Zerafetim", price: 2399, image: p("esarp-085.jpeg"), category: "desenli", isNew: true, description: "Zerafetim açık pembe zemin üzerinde tropikal meyve illüstrasyonları. Ananas, yaprak ve meyve motifleriyle eğlenceli yaz tasarımı.", material: "%100 İpek Twill", size: "90x90 cm", color: "Pembe-Turuncu-Mavi", careInstructions: CARE_SILK },
  { id: 34, name: "Zerafetim Twill Esarp - Botanik Gold", brand: "Zerafetim", price: 2240, image: p("esarp-086.jpeg"), category: "desenli", description: "Zerafetim beyaz zemin üzerinde altın ve gri tonlarında botanik çiçek ve kelebek deseni. Bej bordürlu zarif parça.", material: "%100 İpek Twill", size: "90x90 cm", color: "Beyaz-Gold-Gri", careInstructions: CARE_SILK },
  { id: 35, name: "Zerafetim Twill Esarp - Tren Pop Art Mavi", brand: "Zerafetim", price: 2599, image: p("esarp-087.jpeg"), category: "geometrik", description: "Zerafetim mavi zemin üzerinde kahve vintage tren ve ray motifi. Aynı pop art serinin mavi-yeşil varyasyonu.", material: "%100 İpek Twill", size: "90x90 cm", color: "Mavi-Yeşil-Kahve", careInstructions: CARE_SILK },
  { id: 36, name: "Zerafetim Twill Esarp - Havuz Tropikal Mor", brand: "Zerafetim", price: 2399, oldPrice: 2800, image: p("esarp-088.jpeg"), category: "desenli", isNew: true, description: "Zerafetim mor bordürlu havuz ve tropikal yaprak tasarımı. Çizgili kenarlar ve turkuaz-yeşil yaprak motifleriyle yaz koleksiyonu.", material: "%100 İpek Twill", size: "90x90 cm", color: "Mor-Turkuaz-Pembe", careInstructions: CARE_SILK },
  { id: 37, name: "Zerafetim Twill Esarp - Tropikal Meyve Pembe", brand: "Zerafetim", price: 2399, image: p("esarp-089.jpeg"), category: "desenli", description: "Zerafetim pembe tonlarında tropikal meyve illüstrasyonları. Aynı serinin pastel pembe-mint varyasyonu.", material: "%100 İpek Twill", size: "90x90 cm", color: "Pembe-Mint-Siyah", careInstructions: CARE_SILK },
  { id: 38, name: "Zerafetim Twill Esarp - Botanik Bej", brand: "Zerafetim", price: 2240, image: p("esarp-090.jpeg"), category: "desenli", isNew: true, description: "Zerafetim bej-ten rengi zemin üzerinde siyah botanik çiçek ve kelebek deseni. Sıcak tonlarda sonbahar parçası.", material: "%100 İpek Twill", size: "90x90 cm", color: "Bej-Siyah", careInstructions: CARE_SILK },
  { id: 39, name: "Zerafetim Twill Esarp - Botanik Saks Mavi", brand: "Zerafetim", price: 2399, oldPrice: 2800, image: p("esarp-091.jpeg"), category: "ipek-esarp", isLimited: true, description: "Zerafetim saks mavisi zemin üzerinde botanik çiçek ve kelebek deseni. Aynı serinin canlı mavi varyasyonu. Sınırlı üretim.", material: "%100 İpek Twill", size: "90x90 cm", color: "Saks Mavi-Beyaz", careInstructions: CARE_SILK },
  { id: 40, name: "Zerafetim Twill Esarp - Botanik Turkuaz", brand: "Zerafetim", price: 2240, image: p("esarp-092.jpeg"), category: "desenli", description: "Zerafetim beyaz zemin üzerinde turkuaz-yeşil botanik çiçek ve kelebek deseni. Ferah ve canli.", material: "%100 İpek Twill", size: "90x90 cm", color: "Turkuaz-Beyaz", careInstructions: CARE_SILK },
  { id: 41, name: "Zerafetim Twill Esarp - Tropikal Meyve Siyah-Beyaz", brand: "Zerafetim", price: 2240, image: p("esarp-093.jpeg"), category: "geometrik", description: "Zerafetim siyah-beyaz-gri tonlarında tropikal meyve illüstrasyonları. Monokrom versiyonuyla sofistike.", material: "%100 İpek Twill", size: "90x90 cm", color: "Siyah-Beyaz-Gri", careInstructions: CARE_SILK },
  { id: 42, name: "Zerafetim Twill Esarp - Patchwork Grafik Kahve", brand: "Zerafetim", price: 2599, oldPrice: 3200, image: p("esarp-094.jpeg"), category: "geometrik", isLimited: true, description: "Zerafetim kahverengi grid üzerinde siyah-beyaz çoklu desen kareleri. Chevron, puantiye, çizgi gibi farklı dokular tek esarpta. Sınırlı üretim.", material: "%100 İpek Twill", size: "90x90 cm", color: "Kahve-Siyah-Beyaz", careInstructions: CARE_SILK },

  // ==================== LÜKS MARKA ESARPLARI ====================
  { id: 43, name: "Monogram Esarp - Siyah-Beyaz Klasik", brand: "Premium", price: 4990, oldPrice: 5990, image: p("esarp-073.jpeg"), category: "lux", isLimited: true, description: "Premium siyah zemin üzerinde beyaz monogram motifleri twill ipek esarp. Klasik ve zamansız şıklık.", material: "%100 İpek Twill", size: "90x90 cm", color: "Siyah-Beyaz", careInstructions: CARE_SILK },
  { id: 44, name: "Monogram GG Esarp - Siyah", brand: "Premium", price: 4790, image: p("esarp-074.jpeg"), category: "lux", description: "Premium siyah zemin üzerinde ton-sur-ton GG monogram desenli ipek esarp. Gold yazi bordürlu sofistike tasarım.", material: "%100 İpek Twill", size: "90x90 cm", color: "Siyah-Gold", careInstructions: CARE_SILK },
  { id: 45, name: "Floral Esarp - Bordo Gül Bahcesi", brand: "Premium", price: 5490, oldPrice: 6490, image: p("esarp-075.jpeg"), category: "lux", isLimited: true, description: "Premium bordo zemin üzerinde pembe ve beyaz gül buketi desenli ipek esarp. Krem bordürlu romantik ve zarif.", material: "%100 İpek", size: "90x90 cm", color: "Bordo-Pembe-Krem", careInstructions: CARE_SILK },
  { id: 46, name: "Ekose Esarp - Nova Check Klasik", brand: "Premium", price: 4990, image: p("esarp-076.jpeg"), category: "lux", isNew: true, description: "Premium bej zemin üzerinde klasik ekose kare desen. Lacivert bordürlu zamansız İngiliz tarzı.", material: "%100 İpek Twill", size: "90x90 cm", color: "Bej-Kırmızı-Siyah", careInstructions: CARE_SILK },

  // ==================== EK URUNLER (mevcut fotograflarla) ====================
  { id: 47, name: "Vakko Pamuk İpek Sal - Pudra Gül", brand: "Vakko", price: 1890, image: p("esarp-037.jpeg"), category: "sal", description: "Vakko pamuk-ipek karışımlı sal. Pudra gül deseniyle her kombine zarif bir dokunuş katar. Yumuşacık doku.", material: "Pamuk-İpek", size: "68x200 cm", color: "Pudra", careInstructions: CARE_COTTON },
  { id: 48, name: "Armine Tivil İpek Esarp - Siyah Paisley", brand: "Armine", price: 2700, image: p("esarp-031.jpeg"), category: "ipek-esarp", description: "Armine siyah paisley desenli tivil ipek esarp. Zengin motiflerle zamansız zarafet.", material: "%100 İpek Tivil", size: "90x90 cm", color: "Siyah-Kırmızı-Turuncu", careInstructions: CARE_SILK },
  { id: 49, name: "Armine İpek Sal - Gül Kurusu", brand: "Armine", price: 3400, oldPrice: 4200, image: p("esarp-037.jpeg"), category: "sal", isNew: true, description: "Armine ipek sal, gül kurusu pudra tonunda çiçek deseni. Uzun boy formuyla çok yönlü kullanım.", material: "%100 İpek", size: "70x200 cm", color: "Gül Kurusu-Pudra", careInstructions: CARE_SILK },
  { id: 50, name: "Aker Twill Esarp - Sari Çiçekli", brand: "Aker", price: 1990, image: p("esarp-034.jpeg"), category: "desenli", isNew: true, description: "Aker hardal sari ve kahve zemin üzerinde beyaz çiçek motifli twill esarp.", material: "%100 İpek Twill", size: "90x90 cm", color: "Hardal-Kahve", careInstructions: CARE_SILK },
  { id: 51, name: "Aker Twill Esarp - Siyah Chevron", brand: "Aker", price: 1990, image: p("esarp-035.jpeg"), category: "geometrik", description: "Aker siyah ve gri chevron desenli twill ipek esarp. Zamansiz monokrom.", material: "%100 İpek Twill", size: "90x90 cm", color: "Siyah-Gri", careInstructions: CARE_SILK },

  // ==================== MEVCUT DIGER ESARPLAR ====================
  { id: 52, name: "Vissona Twill Esarp - Şehir Silüeti Lacivert", brand: "Vissona", price: 1449, image: p("esarp-061.jpeg"), category: "ipek-esarp", isNew: true, description: "Vissona lacivert tonlarında şehir silüeti desenli twill ipek esarp. Soyut fırça darbeleriyle modern sanat etkisi.", material: "%100 İpek Twill", size: "90x90 cm", color: "Lacivert-Beyaz", careInstructions: CARE_SILK },
  { id: 53, name: "Vissona Twill Esarp - Şehir Silüeti Yeşil", brand: "Vissona", price: 1449, image: p("esarp-062.jpeg"), category: "ipek-esarp", description: "Vissona yeşil tonlarında şehir silüeti desenli twill ipek esarp. Soyut fırça darbeleriyle doğa ilhamlı.", material: "%100 İpek Twill", size: "90x90 cm", color: "Yeşil-Beyaz", careInstructions: CARE_SILK },
  { id: 54, name: "Vissona Twill Esarp - Şehir Silüeti Bordo", brand: "Vissona", price: 1549, oldPrice: 1999, image: p("esarp-063.jpeg"), category: "ipek-esarp", description: "Vissona bordo tonlarında şehir silüeti desenli twill ipek esarp. Sıcak sonbahar tonlarında.", material: "%100 İpek Twill", size: "90x90 cm", color: "Bordo-Bej", careInstructions: CARE_SILK },
  { id: 55, name: "Vissona Twill Esarp - Şehir Silüeti Turuncu", brand: "Vissona", price: 1449, image: p("esarp-064.jpeg"), category: "ipek-esarp", isNew: true, description: "Vissona turuncu tonlarında şehir silüeti desenli twill ipek esarp. Canlı ve enerjik.", material: "%100 İpek Twill", size: "90x90 cm", color: "Turuncu-Beyaz", careInstructions: CARE_SILK },
  { id: 56, name: "Vissona Twill Esarp - Şehir Silüeti Kahve", brand: "Vissona", price: 1549, image: p("esarp-066.jpeg"), category: "ipek-esarp", description: "Vissona kahve tonlarında şehir silüeti desenli twill ipek esarp. Sonbahar-kış kombini için ideal.", material: "%100 İpek Twill", size: "90x90 cm", color: "Kahve-Bej", careInstructions: CARE_SILK },
  { id: 57, name: "Vissona Twill Esarp - Şehir Silüeti Pembe", brand: "Vissona", price: 1449, image: p("esarp-067.jpeg"), category: "ipek-esarp", description: "Vissona pembe tonlarında şehir silüeti desenli twill ipek esarp. Romantik ve ferah.", material: "%100 İpek Twill", size: "90x90 cm", color: "Pembe-Beyaz", careInstructions: CARE_SILK },
  { id: 58, name: "Vissona Twill Esarp - Şehir Silüeti Siyah", brand: "Vissona", price: 1549, oldPrice: 1999, image: p("esarp-068.jpeg"), category: "ipek-esarp", isLimited: true, description: "Vissona siyah tonlarında şehir silüeti desenli twill ipek esarp. Dramatik ve sofistike. Sınırlı üretim.", material: "%100 İpek Twill", size: "90x90 cm", color: "Siyah-Gri", careInstructions: CARE_SILK },
  { id: 59, name: "Vissona Twill Esarp - Şehir Silüeti Kırmızı", brand: "Vissona", price: 1449, image: p("esarp-069.jpeg"), category: "ipek-esarp", isNew: true, description: "Vissona kırmızı tonlarında şehir silüeti desenli twill ipek esarp. Cesur ve göz alıcı.", material: "%100 İpek Twill", size: "90x90 cm", color: "Kırmızı-Beyaz", careInstructions: CARE_SILK },
  { id: 60, name: "Vissona Twill Esarp - Şehir Silüeti Turkuaz", brand: "Vissona", price: 1549, image: p("esarp-071.jpeg"), category: "ipek-esarp", description: "Vissona turkuaz tonlarında şehir silüeti desenli twill ipek esarp. Yaz mevsiminin ferah renkleri.", material: "%100 İpek Twill", size: "90x90 cm", color: "Turkuaz-Beyaz", careInstructions: CARE_SILK },

  // ==================== KARTAL ESARP KOLEKSIYON (esarp-001 - 006, 008) ====================
  { id: 61, name: "Kartal Esarp Özel Koleksiyon - No.1", brand: "Kartal Esarp", price: 1290, image: p("esarp-001.jpeg"), category: "ipek-esarp", isNew: true, description: "Kartal Esarp özel tasarım koleksiyon parcasi. Zarafetin yeni adresi.", material: "%100 İpek", size: "90x90 cm", color: "Özel Koleksiyon", careInstructions: CARE_SILK },
  { id: 62, name: "Kartal Esarp Özel Koleksiyon - No.2", brand: "Kartal Esarp", price: 1290, image: p("esarp-002.jpeg"), category: "ipek-esarp", description: "Kartal Esarp özel tasarım saten koleksiyon parcasi.", material: "%100 İpek Saten", size: "90x90 cm", color: "Özel Koleksiyon", careInstructions: CARE_SILK },
  { id: 63, name: "Kartal Esarp Özel Koleksiyon - No.3", brand: "Kartal Esarp", price: 1190, image: p("esarp-003.jpeg"), category: "ipek-esarp", description: "Kartal Esarp özel tasarım jersey koleksiyon parcasi.", material: "Jersey İpek", size: "75x200 cm", color: "Özel Koleksiyon", careInstructions: CARE_COTTON },
  { id: 64, name: "Kartal Esarp Özel Koleksiyon - No.4", brand: "Kartal Esarp", price: 1290, image: p("esarp-004.jpeg"), category: "ipek-esarp", description: "Kartal Esarp özel tasarım sifon koleksiyon parcasi.", material: "%100 İpek Sifon", size: "90x90 cm", color: "Özel Koleksiyon", careInstructions: CARE_SILK },
  { id: 65, name: "Kartal Esarp Özel Koleksiyon - No.5", brand: "Kartal Esarp", price: 1190, image: p("esarp-005.jpeg"), category: "ipek-esarp", description: "Kartal Esarp spor koleksiyon parcasi. Günlük kullanım için ideal.", material: "Pamuk-Polyester", size: "90x90 cm", color: "Özel Koleksiyon", careInstructions: CARE_COTTON },
  { id: 66, name: "Kartal Esarp Özel Koleksiyon - No.6", brand: "Kartal Esarp", price: 1390, oldPrice: 1690, image: p("esarp-006.jpeg"), category: "ipek-esarp", isLimited: true, description: "Kartal Esarp sınırlı üretim dokuma koleksiyon parcasi.", material: "Dokuma İpek", size: "90x90 cm", color: "Özel Koleksiyon", careInstructions: CARE_SILK },
  { id: 67, name: "Kartal Esarp Özel Koleksiyon - No.8", brand: "Kartal Esarp", price: 1290, image: p("esarp-008.jpeg"), category: "ipek-esarp", description: "Kartal Esarp özel tasarım koleksiyon parcasi.", material: "%100 İpek", size: "90x90 cm", color: "Özel Koleksiyon", careInstructions: CARE_SILK },

  // ==================== EK ESARPLAR (kalan dosyalar) ====================
  { id: 68, name: "Belli Saf İpek Esarp - Dalga Mavi Klasik", brand: "Belli", price: 1849, oldPrice: 2800, image: p("esarp-028.jpeg"), category: "ipek-esarp", isLimited: true, description: "Belli 2026 koleksiyonu, mavi dalga desenli saf ipek esarp. Sınırlı üretim.", material: "%100 Saf İpek", size: "90x90 cm", color: "Lacivert-Beyaz", careInstructions: CARE_SILK },
  { id: 69, name: "Belli Tivil Esarp - Yeşil Vintage Gul", brand: "Belli", price: 1753, image: p("esarp-029.jpeg"), category: "ipek-esarp", description: "Belli vintage gül buketi desenli tivil ipek esarp. Koyu yeşil zemin.", material: "%100 İpek Twill", size: "90x90 cm", color: "Yeşil-Kırmızı", careInstructions: CARE_SILK },
  { id: 70, name: "Armine Sura İpek Esarp - Mavi Kare", brand: "Armine", price: 2700, image: p("esarp-030.jpeg"), category: "ipek-esarp", description: "Armine buz mavisi tonlarında kare ve fırça darbeli desen. Modern ve sik.", material: "%100 İpek Sura", size: "90x90 cm", color: "Mavi-Buz Mavisi", careInstructions: CARE_SILK },
  { id: 71, name: "Aker Twill Esarp - Osmanlı Lacivert", brand: "Aker", price: 2130, image: p("esarp-032.jpeg"), category: "ipek-esarp", isNew: true, description: "Aker lacivert Osmanlı motifli twill ipek esarp. Turkuaz detaylarla görkemli.", material: "%100 İpek Twill", size: "90x90 cm", color: "Lacivert-Turkuaz", careInstructions: CARE_SILK },
  { id: 72, name: "Zerafetim Viskon Sal - Antrasit Çizgili", brand: "Zerafetim", price: 899, image: p("esarp-035.jpeg"), category: "sal", description: "Zerafetim viskon sal, antrasit gri chevron desen. Günlük kullanım için yumusak doku.", material: "Viskon", size: "75x200 cm", color: "Antrasit-Siyah", careInstructions: CARE_COTTON },
  { id: 73, name: "Vissona Medine Ipegi Sal - Siyah", brand: "Vissona", price: 349, image: p("esarp-035.jpeg"), category: "sal", description: "Vissona siyah medine ipegi sal. Her kombine uyum saglayan temel parça.", material: "Medine Ipegi", size: "75x200 cm", color: "Siyah", careInstructions: CARE_COTTON },
  { id: 74, name: "Zerafetim Viskon Sal - Pudra Gül", brand: "Zerafetim", price: 849, image: p("esarp-037.jpeg"), category: "sal", isNew: true, description: "Zerafetim viskon sal, pudra gül deseni. Hafif ve her mevsim.", material: "Viskon", size: "75x200 cm", color: "Pudra-Somon", careInstructions: CARE_COTTON },
  { id: 75, name: "Belli Fresh Berlin Sal - Siyah", brand: "Belli", price: 264, image: p("esarp-036.jpeg"), category: "sal", description: "Belli Fresh Berlin serisi sal. Siyah-beyaz çizgili, pembe bordür.", material: "Pamuk Karisim", size: "70x200 cm", color: "Siyah-Beyaz", careInstructions: CARE_COTTON },
  { id: 76, name: "Vissona Medine Ipegi Sal - Pudra", brand: "Vissona", price: 399, image: p("esarp-037.jpeg"), category: "sal", description: "Vissona lux medine ipegi sal. Pudra çiçek tonlarında günlük kullanıma uygun.", material: "Medine Ipegi", size: "75x200 cm", color: "Pudra", careInstructions: CARE_COTTON },
  { id: 77, name: "Vakko Twill İpek Esarp - Kareli Vizon", brand: "Vakko", price: 2390, image: p("esarp-041.jpeg"), category: "geometrik", description: "Vakko vizon ve kahve tonlarında kareli twill ipek esarp. Sonbahar-kış için sıcak ve zarif.", material: "%100 İpek Twill", size: "90x90 cm", color: "Vizon-Kahve", careInstructions: CARE_SILK },
  { id: 78, name: "Vakko Twill İpek Esarp - Modern Soyut", brand: "Vakko", price: 2490, oldPrice: 2990, image: p("esarp-044.jpeg"), category: "ipek-esarp", isNew: true, description: "Vakko modern soyut desenli twill ipek esarp. Canlı renklerle dinamik ve göz alıcı.", material: "%100 İpek Twill", size: "90x90 cm", color: "Çok Renkli", careInstructions: CARE_SILK },
  { id: 79, name: "Vakko Twill İpek Esarp - Klasik Bordür", brand: "Vakko", price: 2290, image: p("esarp-046.jpeg"), category: "ipek-esarp", description: "Vakko klasik bordür desenli twill ipek esarp. Zarif ve zamansız.", material: "%100 İpek Twill", size: "90x90 cm", color: "Klasik", careInstructions: CARE_SILK },
  { id: 80, name: "Vakko Twill İpek Esarp - Doga Ilhamli", brand: "Vakko", price: 2690, oldPrice: 3290, image: p("esarp-054.jpeg"), category: "desenli", isLimited: true, description: "Vakko doğa ilhamlı desenlerle suslenmiş twill ipek esarp. Sınırlı üretim.", material: "%100 İpek Twill", size: "90x90 cm", color: "Doga Tonlari", careInstructions: CARE_SILK },
  { id: 81, name: "Vissona Twill Esarp - Soyut Grafik", brand: "Vissona", price: 1349, image: p("esarp-057.jpeg"), category: "geometrik", description: "Vissona soyut grafik desenli twill ipek esarp. Modern sanat etkisi.", material: "%100 İpek Twill", size: "90x90 cm", color: "Çok Renkli", careInstructions: CARE_SILK },
  { id: 82, name: "Vissona Twill Esarp - Soyut Fırça", brand: "Vissona", price: 1449, oldPrice: 1999, image: p("esarp-058.jpeg"), category: "desenli", isNew: true, description: "Vissona soyut fırça darbeleri desenli twill ipek esarp. Sanatsal ve ozgun.", material: "%100 İpek Twill", size: "90x90 cm", color: "Çok Renkli", careInstructions: CARE_SILK },
];

export function getProductsByCategory(category: string): Product[] {
  return allProducts.filter((p) => p.category === category);
}

export function getNewProducts(): Product[] {
  return allProducts.filter((p) => p.isNew);
}

export function getLimitedProducts(): Product[] {
  return allProducts.filter((p) => p.isLimited);
}

export function getProductsByBrand(brand: string): Product[] {
  return allProducts.filter((p) => p.brand.toLowerCase() === brand.toLowerCase());
}

export function getProductById(id: number): Product | undefined {
  return allProducts.find((p) => p.id === id);
}

export function getSimilarProducts(product: Product, limit = 4): Product[] {
  return allProducts
    .filter((p) => p.id !== product.id && (p.category === product.category || p.brand === product.brand))
    .slice(0, limit);
}

export function handleWhatsAppOrder(product: Product) {
  return getProductOrderWhatsAppUrl(product.name);
}
