export interface Product {
  id: number;
  name: string;
  brand: string;
  price: number;
  oldPrice?: number;
  image: string;
  category: string;
  isNew?: boolean;
  isLimited?: boolean;
  description: string;
  material: string;
  size: string;
  color: string;
  careInstructions: string;
}

const CARE_SILK = "Kuru temizleme onerilir. Elde yikama yapilacaksa ilk soguk suyla nazikce yikayin. Ters cevirip dusuk isida utuleyin. Dogrudan gunes isiginda kurutmayin.";
const CARE_COTTON = "30 derecede yikanabilir. Golgede kurutun. Orta isida utuleyin.";

function p(file: string) {
  return `/products/${file}`;
}

export const allProducts: Product[] = [
  // ==================== VAKKO ====================
  { id: 1, name: "Vakko Twill Ipek Esarp - Geometrik Renkli", brand: "Vakko", price: 2490, oldPrice: 2990, image: p("esarp-013.jpeg"), category: "saten", isNew: true, description: "Vakko imzali %100 twill ipek esarp. Canli yesil, mavi, kirmizi ve sari geometrik bloklar. Cesur tasarimla gunluk kombinden davetlere her ortamda goz doldurun.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Cok Renkli Geometrik", careInstructions: CARE_SILK },
  { id: 2, name: "Vakko Twill Ipek Esarp - Gul Deseni Pudra", brand: "Vakko", price: 2290, image: p("esarp-014.jpeg"), category: "sifon", description: "Vakko pudra tonunda romantik gul deseni twill ipek esarp. Pembe guller bej zemin uzerinde zarif bir goruntu olusturur.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Pudra-Pembe", careInstructions: CARE_SILK },
  { id: 3, name: "Vakko Twill Ipek Esarp - Cicek Buketi Lacivert", brand: "Vakko", price: 2890, oldPrice: 3490, image: p("esarp-016.jpeg"), category: "saten", isLimited: true, description: "Vakko lacivert zemin uzerinde beyaz, mavi ve mor cicek buketi desenli twill ipek esarp. Sanatsal cicek motifleri ve leopar detaylariyla sinirli uretim.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Lacivert-Mavi-Beyaz", careInstructions: CARE_SILK },
  { id: 4, name: "Vakko Twill Ipek Esarp - Bahar Cicekleri", brand: "Vakko", price: 2690, image: p("esarp-017.jpeg"), category: "sifon", isNew: true, description: "Vakko krem zemin uzerinde turkuaz, kirmizi ve mor bahar cicekleri motifli twill ipek esarp. Turuncu bordur ile canli bir goruntu.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Krem-Turkuaz-Kirmizi", careInstructions: CARE_SILK },
  { id: 5, name: "Vakko Twill Ipek Esarp - Mavi Puantiye", brand: "Vakko", price: 2490, image: p("esarp-018.jpeg"), category: "saten", description: "Vakko mavi tonlarinda 3D puantiye desenli twill ipek esarp. Art deco ilhamli geometrik cizgiler ve mavi-turkuaz kure motifleri.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Mavi-Turkuaz", careInstructions: CARE_SILK },
  { id: 6, name: "Vakko Twill Ipek Esarp - Konfeti Siyah", brand: "Vakko", price: 2790, oldPrice: 3290, image: p("esarp-019.jpeg"), category: "saten", isNew: true, description: "Vakko siyah zemin uzerinde renkli konfeti damlalari desenli twill ipek esarp. Spiral efektli benzersiz pop-art tasarimi.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Siyah-Cok Renkli", careInstructions: CARE_SILK },
  { id: 7, name: "Vakko Twill Ipek Esarp - Op Art Spiral", brand: "Vakko", price: 2990, oldPrice: 3690, image: p("esarp-020.jpeg"), category: "saten", isLimited: true, description: "Vakko op-art ilhamli spiral geometrik desenli twill ipek esarp. Siyah-beyaz, kirmizi, yesil, mavi ve turuncu kontrast renklerle dikkat cekici sinirli uretim.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Cok Renkli Op Art", careInstructions: CARE_SILK },
  { id: 8, name: "Vakko Twill Ipek Esarp - Modern Blok Turuncu-Mavi", brand: "Vakko", price: 2490, image: p("esarp-021.jpeg"), category: "sifon", description: "Vakko modern renk bloklari desenli twill ipek esarp. Turuncu, mavi ve buz mavisi cesur renk gecisleri.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Turuncu-Mavi", careInstructions: CARE_SILK },
  { id: 9, name: "Vakko Twill Ipek Esarp - Puantiye Lacivert", brand: "Vakko", price: 2290, image: p("esarp-022.jpeg"), category: "saten", description: "Vakko lacivert-buz mavisi tonlarinda puantiye desen esarp. Halftone noktalar ve geometrik zig-zag detaylariyla modern bir klasik.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Lacivert-Gri", careInstructions: CARE_SILK },
  { id: 10, name: "Vakko Twill Ipek Esarp - Cizgili Kahve Toprak", brand: "Vakko", price: 2390, image: p("esarp-023.jpeg"), category: "dokuma", isNew: true, description: "Vakko kahverengi ve lacivert cizgili twill ipek esarp. Karamel, toprak ve kiremit tonlarinda sicak bir goruntu.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Kahve-Lacivert-Kiremit", careInstructions: CARE_SILK },
  { id: 11, name: "Vakko Twill Ipek Esarp - Buyuk Puantiye Mavi-Beyaz", brand: "Vakko", price: 2490, image: p("esarp-024.jpeg"), category: "saten", description: "Vakko lacivert ve beyaz buyuk puantiye desenli twill ipek esarp. Kontrast puantiyelerin zamansiz sikligiyla modern bir klasik.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Lacivert-Beyaz", careInstructions: CARE_SILK },
  { id: 12, name: "Vakko Twill Ipek Esarp - Etnik Madalyon Kirmizi-Mavi", brand: "Vakko", price: 3190, oldPrice: 3890, image: p("esarp-025.jpeg"), category: "saten", isLimited: true, description: "Vakko kirmizi, mavi ve altin tonlarinda etnik madalyon desenli twill ipek esarp. Kulturel motiflerden ilham alan premium sinirli uretim.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Kirmizi-Mavi-Gold", careInstructions: CARE_SILK },
  { id: 13, name: "Vakko Twill Ipek Esarp - Zincir Turuncu", brand: "Vakko", price: 2690, image: p("esarp-026.jpeg"), category: "saten", isNew: true, description: "Vakko turuncu ve gri tonlarinda zincir motifli twill ipek esarp. Hermes ilhamli kemer ve zincir desenleriyle sik bir tasarim.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Turuncu-Gri", careInstructions: CARE_SILK },
  { id: 14, name: "Vakko Twill Ipek Esarp - Paisley Kirmizi-Bordo", brand: "Vakko", price: 2890, image: p("esarp-027.jpeg"), category: "dokuma", description: "Vakko kirmizi ve bordo tonlarinda zengin paisley desenli twill ipek esarp. Geleneksel Osmanli ve Hint motiflerinin modern yorumu.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Kirmizi-Bordo-Gold", careInstructions: CARE_SILK },
  { id: 15, name: "Vakko Twill Ipek Esarp - Kareli Buz Mavisi", brand: "Vakko", price: 2290, image: p("esarp-030.jpeg"), category: "sifon", description: "Vakko buz mavisi zemin uzerinde sulu boya firca darbeleriyle kare desen twill ipek esarp. Minimalist ve modern.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Buz Mavisi-Lacivert", careInstructions: CARE_SILK },
  { id: 16, name: "Vakko Twill Ipek Esarp - Paisley Siyah Toprak", brand: "Vakko", price: 2790, oldPrice: 3490, image: p("esarp-031.jpeg"), category: "dokuma", isNew: true, description: "Vakko siyah zemin uzerinde kirmizi, turuncu ve altin paisley desenleri. Zengin dokusu ve detayli motifleriyle premium bir parca.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Siyah-Kirmizi-Turuncu", careInstructions: CARE_SILK },
  { id: 17, name: "Vakko Twill Ipek Esarp - Osmanli Motif Lacivert", brand: "Vakko", price: 2990, image: p("esarp-032.jpeg"), category: "saten", description: "Vakko lacivert zemin uzerinde turkuaz Osmanli motifleri twill ipek esarp. Inci ve mucevher detaylariyla gorkemli bir tasarim.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Lacivert-Turkuaz", careInstructions: CARE_SILK },
  { id: 18, name: "Vakko Twill Ipek Esarp - Daire Geometrik Bej", brand: "Vakko", price: 2190, image: p("esarp-033.jpeg"), category: "sifon", description: "Vakko bej-gold tonlarinda ic ice gecen daire motifleri twill ipek esarp. Yumusak ve sik bir renk paletiyle minimalist zarafet.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Bej-Gold", careInstructions: CARE_SILK },
  { id: 19, name: "Vakko Twill Ipek Esarp - Cicekli Hardal-Kahve", brand: "Vakko", price: 2590, oldPrice: 3090, image: p("esarp-034.jpeg"), category: "sifon", isNew: true, description: "Vakko hardal ve kahverengi zemin uzerinde beyaz cicek motifleri twill ipek esarp. Mavi bordur ile dogadan ilham alan sonbahar tasarimi.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Hardal-Kahve", careInstructions: CARE_SILK },
  { id: 20, name: "Vakko Twill Ipek Esarp - Chevron Siyah-Gri", brand: "Vakko", price: 2490, image: p("esarp-035.jpeg"), category: "saten", description: "Vakko siyah ve gri tonlarinda chevron (ok ucu) geometrik desenli twill ipek esarp. Monokrom siklin temsilcisi.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Siyah-Gri-Beyaz", careInstructions: CARE_SILK },
  { id: 21, name: "Vakko Twill Ipek Esarp - Cizgili Siyah-Beyaz Mini", brand: "Vakko", price: 1990, image: p("esarp-036.jpeg"), category: "sifon", description: "Vakko siyah-beyaz dalga cizgili twill ipek esarp. Pembe bordur detayiyla minimalist ve modern. Kompakt boyutuyla her kombine uyumlu.", material: "%100 Ipek Twill", size: "70x70 cm", color: "Siyah-Beyaz-Pembe", careInstructions: CARE_SILK },
  { id: 22, name: "Vakko Twill Ipek Esarp - Pudra Gul Buketi", brand: "Vakko", price: 2390, oldPrice: 2890, image: p("esarp-037.jpeg"), category: "sifon", isNew: true, description: "Vakko pudra ve somon tonlarinda buyuk gul buketi desenli twill ipek esarp. Vakko ozel kirmizi cantasiyla sunulan premium parca.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Pudra-Somon", careInstructions: CARE_SILK },
  { id: 23, name: "Vakko Twill Ipek Esarp - Kazayagi Mavi", brand: "Vakko", price: 2690, image: p("esarp-040.jpeg"), category: "saten", description: "Vakko mavi tonlarinda patlamis kazayagi (houndstooth) desenli twill ipek esarp. Lacivert ve turkuaz tonlarinda dinamik ve modern.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Mavi-Lacivert-Turkuaz", careInstructions: CARE_SILK },
  { id: 24, name: "Vakko Twill Ipek Esarp - Isik Huzmesi Mavi-Yesil", brand: "Vakko", price: 2790, oldPrice: 3390, image: p("esarp-045.jpeg"), category: "saten", isLimited: true, description: "Vakko mavi ve yesil tonlarinda isik huzmesi efektli twill ipek esarp. Alt kisimda siyah-beyaz satranc deseniyle avangard bir tasarim.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Mavi-Yesil-Beyaz", careInstructions: CARE_SILK },

  // ==================== BELLI ====================
  { id: 25, name: "Belli Twill Ipek Esarp - Dalga Mavi", brand: "Belli", price: 1753, image: p("esarp-028.jpeg"), category: "saten", isNew: true, description: "Belli lacivert zemin uzerinde beyaz dalga ve cicek bordur desenli twill ipek esarp. Zarif dalga motifleri ic ice gecen katmanlar olusturur.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Lacivert-Beyaz", careInstructions: CARE_SILK },
  { id: 26, name: "Belli Twill Ipek Esarp - Vintage Gul Yesil-Kahve", brand: "Belli", price: 1849, oldPrice: 2400, image: p("esarp-029.jpeg"), category: "sifon", description: "Belli koyu yesil zemin uzerinde vintage gul buketi desenli twill ipek esarp. Kirmizi, pembe ve sari guller sulu boya efektinde.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Yesil-Kirmizi-Pembe", careInstructions: CARE_SILK },

  // ==================== ARMINE ====================
  { id: 27, name: "Armine Twill Ipek Esarp - Gul Buketi Bordo", brand: "Armine", price: 2900, oldPrice: 4900, image: p("esarp-050.jpeg"), category: "saten", isNew: true, description: "Armine bordo cerceve icerisinde kirmizi ve turuncu gul buketi desenli twill ipek esarp. Impressionist sanat tarzinda sulu boya gulleri.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Bordo-Kirmizi-Turuncu", careInstructions: CARE_SILK },

  // ==================== VISSONA ====================
  { id: 28, name: "Vissona Twill Ipek Esarp - Graffiti Turuncu-Fuşya", brand: "Vissona", price: 1349, oldPrice: 1999, image: p("esarp-055.jpeg"), category: "saten", isNew: true, description: "Vissona %100 twill ipek esarp (Kod: 51403). Siyah zemin uzerinde turuncu ve fusya graffiti harfler. 90x90 cm, kargo ucretsiz.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Siyah-Turuncu-Fusya", careInstructions: CARE_SILK },
  { id: 29, name: "Vissona Twill Ipek Esarp - Soyut Sehir Gri", brand: "Vissona", price: 1449, image: p("esarp-060.jpeg"), category: "saten", description: "Vissona siyah ve gri tonlarinda soyut sehir silueti desenli twill ipek esarp. Modern cizgiler ve firca darbeleriyle avangard.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Gri-Siyah-Beyaz", careInstructions: CARE_SILK },
  { id: 30, name: "Vissona Twill Ipek Esarp - Soyut Sehir Mavi", brand: "Vissona", price: 1449, image: p("esarp-065.jpeg"), category: "sifon", isNew: true, description: "Vissona mavi ve bej tonlarinda soyut sehir silueti desenli twill ipek esarp. Ayni serinin mavi varyasyonu.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Mavi-Bej-Beyaz", careInstructions: CARE_SILK },
  { id: 31, name: "Vissona Twill Ipek Esarp - Soyut Sehir Pembe-Mavi", brand: "Vissona", price: 1549, oldPrice: 1999, image: p("esarp-070.jpeg"), category: "sifon", description: "Vissona pembe ve mavi tonlarinda soyut sehir silueti desenli twill ipek esarp. Canli renk kombinasyonuyla goz alici.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Pembe-Mavi", careInstructions: CARE_SILK },
  { id: 32, name: "Vissona Twill Ipek Esarp - Soyut Fusya-Mavi-Yesil", brand: "Vissona", price: 1549, image: p("esarp-072.jpeg"), category: "saten", isNew: true, description: "Vissona fusya, mavi ve yesil tonlarinda soyut geometrik desenli twill ipek esarp. Model uzerinde gosterilen ozel kombinleme stili.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Fusya-Mavi-Yesil", careInstructions: CARE_SILK },

  // ==================== ZERAFETIM ====================
  { id: 33, name: "Zerafetim Twill Ipek Esarp - Siyah Grafik", brand: "Zerafetim", price: 2240, oldPrice: 2800, image: p("esarp-015.jpeg"), category: "saten", description: "Zerafetim siyah zemin uzerinde bej/krem grafik cizgiler ve ok motifleri twill ipek esarp. Cesur ve modern bir tasarim.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Siyah-Bej", careInstructions: CARE_SILK },
  { id: 34, name: "Zerafetim Twill Ipek Esarp - Gri Geometrik", brand: "Zerafetim", price: 2240, image: p("esarp-015.jpeg"), category: "saten", isNew: true, description: "Zerafetim gri tonlarinda geometrik motifler ve develer siluetiyle twill ipek esarp. Notr ve sik.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Gri-Siyah", careInstructions: CARE_SILK },

  // ==================== EK VAKKO URUNLER (diger fiyat segmentleri) ====================
  { id: 35, name: "Vakko Pamuk Ipek Sal - Pudra", brand: "Vakko", price: 1890, image: p("esarp-014.jpeg"), category: "jersey", description: "Vakko pamuk-ipek karisimli sal. Pudra gul deseniyle her kombine zarif bir dokunuk katar. 68x200 cm ebatinda yumusacik doku.", material: "Pamuk-Ipek", size: "68x200 cm", color: "Pudra", careInstructions: CARE_COTTON },
  { id: 36, name: "Vakko Pamuk Ipek Sal - Vizon Cizgili", brand: "Vakko", price: 1890, image: p("esarp-023.jpeg"), category: "jersey", isNew: true, description: "Vakko pamuk-ipek sal, vizon ve kahve cizgili desen. Sonbahar kombinleri icin ideal sicaklik ve yumusaklik.", material: "Pamuk-Ipek", size: "68x200 cm", color: "Vizon-Kahve", careInstructions: CARE_COTTON },
  { id: 37, name: "Vakko Twill Ipek Esarp - Geometrik Retro", brand: "Vakko", price: 2590, image: p("esarp-013.jpeg"), category: "saten", description: "Vakko retro geometrik bloklarla suslenmis twill ipek esarp. Yesil, sari, kirmizi ve mavi kontrastla 70'ler estetiginden ilham.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Retro Cok Renkli", careInstructions: CARE_SILK },

  // ==================== EK ARMINE (zincir desen - esarp-015'teki mavi Armine) ====================
  { id: 38, name: "Armine Twill Ipek Esarp - Zincir Mavi", brand: "Armine", price: 2700, image: p("esarp-015.jpeg"), category: "sifon", isNew: true, description: "Armine buz mavisi zemin uzerinde renkli zincir halkalari desenli twill ipek esarp. Pembe, mor ve turkuaz zincirlerle modern.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Buz Mavisi-Cok Renkli", careInstructions: CARE_SILK },
  { id: 39, name: "Armine Sportwear Esarp - Vizon", brand: "Armine", price: 549, image: p("esarp-033.jpeg"), category: "spor", description: "Armine spor serisi esarp. Bej tonlarinda geometrik daire deseniyle gunluk kullanima uygun, hafif ve rahat.", material: "Pamuk-Polyester", size: "90x90 cm", color: "Bej", careInstructions: CARE_COTTON },
  { id: 40, name: "Armine Tivil Ipek Esarp - Cicekli Pembe", brand: "Armine", price: 2900, oldPrice: 4900, image: p("esarp-014.jpeg"), category: "sifon", description: "Armine gul deseni tivil ipek esarp. Pudra tonlarinda romantik bir goruntu sunar.", material: "%100 Ipek Tivil", size: "90x90 cm", color: "Pudra-Pembe", careInstructions: CARE_SILK },
  { id: 41, name: "Armine Sura Ipek Esarp - Mavi Geometrik", brand: "Armine", price: 2700, image: p("esarp-018.jpeg"), category: "saten", description: "Armine geometrik daire desenli sura ipek esarp. Mavi ve turkuaz tonlarinda modern.", material: "%100 Ipek Sura", size: "90x90 cm", color: "Mavi-Turkuaz", careInstructions: CARE_SILK },
  { id: 42, name: "Armine Tivil Ipek Esarp - Sonbahar Paleti", brand: "Armine", price: 3200, oldPrice: 4900, image: p("esarp-027.jpeg"), category: "saten", isLimited: true, description: "Armine sonbahar tonlarinda paisley motifli tivil ipek esarp. Bordo, kirmizi ve gold tonlarinda sinirli uretim.", material: "%100 Ipek Tivil", size: "90x90 cm", color: "Bordo-Kirmizi-Gold", careInstructions: CARE_SILK },
  { id: 43, name: "Armine Sportwear Esarp - Lacivert", brand: "Armine", price: 479, image: p("esarp-022.jpeg"), category: "spor", description: "Armine spor esarp, lacivert puantiye desen. Is ve gunluk yasam icin pratik.", material: "Pamuk-Polyester", size: "90x90 cm", color: "Lacivert-Beyaz", careInstructions: CARE_COTTON },
  { id: 44, name: "Armine Tivil Esarp - Siyah Paisley", brand: "Armine", price: 2700, image: p("esarp-031.jpeg"), category: "saten", description: "Armine siyah paisley desenli tivil ipek esarp. Zengin motiflerle zamansiz zarafet.", material: "%100 Ipek Tivil", size: "90x90 cm", color: "Siyah-Kirmizi-Turuncu", careInstructions: CARE_SILK },
  { id: 45, name: "Armine Ipek Sal - Gul Kurusu", brand: "Armine", price: 3400, oldPrice: 4200, image: p("esarp-037.jpeg"), category: "sifon", isNew: true, description: "Armine ipek sal, gul kurusu pudra tonunda cicek deseni. Uzun boy formuyla cok yonlu kullanim.", material: "%100 Ipek", size: "70x200 cm", color: "Gul Kurusu-Pudra", careInstructions: CARE_SILK },

  // ==================== EK AKER ====================
  { id: 46, name: "Aker Twill Ipek Esarp - Geometrik Blok", brand: "Aker", price: 1990, image: p("esarp-021.jpeg"), category: "sifon", description: "Aker %100 ipek twill esarp. Turuncu ve mavi modern geometrik blok desen.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Turuncu-Mavi", careInstructions: CARE_SILK },
  { id: 47, name: "Aker Ipek Sura Esarp - Sonbahar Kis", brand: "Aker", price: 2600, oldPrice: 3990, image: p("esarp-023.jpeg"), category: "saten", isNew: true, description: "Aker 2025-2026 Sonbahar-Kis koleksiyonu. Kahve ve lacivert cizgili desen.", material: "%100 Ipek Sura", size: "90x90 cm", color: "Kahve-Lacivert", careInstructions: CARE_SILK },
  { id: 48, name: "Aker Twill Esarp - Sari Cicekli", brand: "Aker", price: 1990, image: p("esarp-034.jpeg"), category: "sifon", isNew: true, description: "Aker hardal sari ve kahve zemin uzerinde beyaz cicek motifli twill esarp.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Hardal-Kahve", careInstructions: CARE_SILK },
  { id: 49, name: "Aker Premium Twill Esarp - Kirmizi Madalyon", brand: "Aker", price: 3900, oldPrice: 4990, image: p("esarp-025.jpeg"), category: "saten", isLimited: true, description: "Aker premium seri kirmizi ve mavi madalyon desenli twill ipek esarp. Sinirli sayida.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Kirmizi-Mavi-Gold", careInstructions: CARE_SILK },
  { id: 50, name: "Aker Twill Esarp - Turkuaz Dalga", brand: "Aker", price: 2130, image: p("esarp-040.jpeg"), category: "sifon", description: "Aker turkuaz tonlarinda kazayagi desenli twill ipek esarp. Dinamik ve ferah.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Turkuaz-Mavi", careInstructions: CARE_SILK },
  { id: 51, name: "Aker Twill Esarp - Siyah Chevron", brand: "Aker", price: 1990, image: p("esarp-035.jpeg"), category: "saten", description: "Aker siyah ve gri chevron desenli twill ipek esarp. Zamansiz monokrom.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Siyah-Gri", careInstructions: CARE_SILK },
  { id: 52, name: "Aker Ipek Sal - Bej Dogal", brand: "Aker", price: 2400, image: p("esarp-033.jpeg"), category: "dokuma", isNew: true, description: "Aker bej tonunda daire motifli ipek sal. Kis kombinlerinin sicak tamamlayicisi.", material: "%100 Ipek", size: "70x200 cm", color: "Bej-Gold", careInstructions: CARE_SILK },

  // ==================== EK VISSONA ====================
  { id: 53, name: "Vissona Twill Ipek Esarp - Leopar Mavi", brand: "Vissona", price: 1349, oldPrice: 1999, image: p("esarp-032.jpeg"), category: "saten", description: "Vissona lacivert ve turkuaz Osmanli motifli twill ipek esarp.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Lacivert-Turkuaz", careInstructions: CARE_SILK },
  { id: 54, name: "Vissona Medine Ipegi Sal - Pudra", brand: "Vissona", price: 399, image: p("esarp-037.jpeg"), category: "jersey", description: "Vissona lux medine ipegi sal. Pudra cicek tonlarinda gunluk kullanima uygun.", material: "Medine Ipegi", size: "75x200 cm", color: "Pudra", careInstructions: CARE_COTTON },
  { id: 55, name: "Vissona Twill Esarp - Barok Deseni", brand: "Vissona", price: 1499, oldPrice: 1999, image: p("esarp-027.jpeg"), category: "saten", description: "Vissona barok paisley desenli twill ipek esarp. Kirmizi-bordo gorkemli tasarim.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Bordo-Kirmizi", careInstructions: CARE_SILK },
  { id: 56, name: "Vissona Medine Ipegi Sal - Siyah", brand: "Vissona", price: 349, image: p("esarp-035.jpeg"), category: "jersey", description: "Vissona siyah medine ipegi sal. Her kombine uyum saglayan temel parca.", material: "Medine Ipegi", size: "75x200 cm", color: "Siyah", careInstructions: CARE_COTTON },
  { id: 57, name: "Vissona Twill Esarp - Isik Huzmesi", brand: "Vissona", price: 1549, image: p("esarp-045.jpeg"), category: "saten", isNew: true, description: "Vissona mavi-yesil isik huzmesi desenli twill ipek esarp. Dikkat cekici avangard tasarim.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Mavi-Yesil", careInstructions: CARE_SILK },
  { id: 58, name: "Vissona Fresh Sal - Pembe Gul", brand: "Vissona", price: 1449, image: p("esarp-014.jpeg"), category: "sifon", description: "Vissona fresh ipek sal, pembe gul deseninde. Romantik ve zarif.", material: "%100 Ipek", size: "70x200 cm", color: "Pudra-Pembe", careInstructions: CARE_SILK },
  { id: 59, name: "Vissona Medine Ipegi Sal - Lacivert", brand: "Vissona", price: 379, image: p("esarp-022.jpeg"), category: "jersey", description: "Vissona lacivert puantiye medine ipegi sal. Klasik ve her mevsim.", material: "Medine Ipegi", size: "75x200 cm", color: "Lacivert", careInstructions: CARE_COTTON },
  { id: 60, name: "Vissona Twill Esarp - Kirmizi Zincir", brand: "Vissona", price: 1549, oldPrice: 1999, image: p("esarp-026.jpeg"), category: "saten", isLimited: true, description: "Vissona turuncu zincir motifli twill ipek esarp. Sinirli uretim.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Turuncu-Gri", careInstructions: CARE_SILK },

  // ==================== EK BELLI ====================
  { id: 61, name: "Belli Twill Ipek Esarp - Cicekli Bordo", brand: "Belli", price: 1753, image: p("esarp-050.jpeg"), category: "sifon", isNew: true, description: "Belli bordo cercevede gul buketi desenli tivil ipek esarp. Yaz sezonunun canli parcasi.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Bordo-Kirmizi", careInstructions: CARE_SILK },
  { id: 62, name: "Belli Saf Ipek Esarp - Dalga Mavi Klasik", brand: "Belli", price: 1849, oldPrice: 2800, image: p("esarp-028.jpeg"), category: "saten", isLimited: true, description: "Belli 2026 koleksiyonu, mavi dalga desenli saf ipek esarp. Sinirli uretim.", material: "%100 Saf Ipek", size: "90x90 cm", color: "Lacivert-Beyaz", careInstructions: CARE_SILK },
  { id: 63, name: "Belli Fresh Monogram Sal", brand: "Belli", price: 264, image: p("esarp-033.jpeg"), category: "spor", description: "Belli fresh monogram sal. Bej daire deseninde hafif ve sik.", material: "Pamuk Karisim", size: "70x200 cm", color: "Bej-Gold", careInstructions: CARE_COTTON },
  { id: 64, name: "Belli Tivil Esarp - Yesil Vintage Gul", brand: "Belli", price: 1753, image: p("esarp-029.jpeg"), category: "sifon", description: "Belli vintage gul buketi desenli tivil ipek esarp. Koyu yesil zemin.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Yesil-Kirmizi", careInstructions: CARE_SILK },
  { id: 65, name: "Belli Ipek Esarp - Puantiye Lacivert", brand: "Belli", price: 1849, image: p("esarp-024.jpeg"), category: "saten", isNew: true, description: "Belli lacivert-beyaz puantiye desenli ipek esarp. Zamansiz klasik.", material: "%100 Ipek", size: "90x90 cm", color: "Lacivert-Beyaz", careInstructions: CARE_SILK },
  { id: 66, name: "Belli Fresh Berlin Sal - Siyah", brand: "Belli", price: 264, image: p("esarp-036.jpeg"), category: "spor", description: "Belli Fresh Berlin serisi sal. Siyah-beyaz cizgili, pembe bordur.", material: "Pamuk Karisim", size: "70x200 cm", color: "Siyah-Beyaz", careInstructions: CARE_COTTON },
  { id: 67, name: "Belli Tivil Esarp - Konfeti Pop Art", brand: "Belli", price: 1753, image: p("esarp-019.jpeg"), category: "saten", description: "Belli renkli konfeti pop-art desenli tivil ipek esarp. Eglenceli ve cesur.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Siyah-Cok Renkli", careInstructions: CARE_SILK },
  { id: 68, name: "Belli Saf Ipek Esarp - Bordo Paisley", brand: "Belli", price: 2100, oldPrice: 2800, image: p("esarp-027.jpeg"), category: "dokuma", description: "Belli bordo paisley desenli saf ipek esarp. Zengin ve sofistike.", material: "%100 Saf Ipek", size: "90x90 cm", color: "Bordo-Gold", careInstructions: CARE_SILK },

  // ==================== EK ZERAFETIM ====================
  { id: 69, name: "Zerafetim Couture Twill Esarp - Siyah Grafik Bold", brand: "Zerafetim", price: 2399, image: p("esarp-015.jpeg"), category: "saten", isNew: true, description: "Zerafetim couture twill ipek esarp. Siyah zemin uzerinde cesur grafik cizgiler.", material: "%100 Ipek Couture Twill", size: "90x90 cm", color: "Siyah-Bej", careInstructions: CARE_SILK },
  { id: 70, name: "Zerafetim Twill Esarp - Mavi Akdeniz", brand: "Zerafetim", price: 2240, image: p("esarp-018.jpeg"), category: "sifon", description: "Zerafetim Akdeniz mavisi puantiye desenli twill ipek esarp.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Mavi-Turkuaz", careInstructions: CARE_SILK },
  { id: 71, name: "Zerafetim Yun Ipek Sal - Krem Daire", brand: "Zerafetim", price: 1749, image: p("esarp-033.jpeg"), category: "dokuma", isLimited: true, description: "Zerafetim yun-ipek karisim sal. Bej daire motiflerinde sinirli uretim.", material: "Yun-Ipek", size: "70x200 cm", color: "Krem-Gold", careInstructions: CARE_SILK },
  { id: 72, name: "Zerafetim Twill Esarp - Pembe Gul Romantik", brand: "Zerafetim", price: 2240, image: p("esarp-014.jpeg"), category: "sifon", isNew: true, description: "Zerafetim pembe gul deseniyle romantik twill ipek esarp.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Pudra-Pembe", careInstructions: CARE_SILK },
  { id: 73, name: "Zerafetim Viskon Sal - Antrasit Cizgili", brand: "Zerafetim", price: 899, image: p("esarp-035.jpeg"), category: "jersey", description: "Zerafetim viskon sal, antrasit gri chevron desen. Gunluk kullanim icin yumusak doku.", material: "Viskon", size: "75x200 cm", color: "Antrasit-Siyah", careInstructions: CARE_COTTON },
  { id: 74, name: "Zerafetim Couture Esarp - Bordo Etnik", brand: "Zerafetim", price: 2599, oldPrice: 2800, image: p("esarp-025.jpeg"), category: "saten", description: "Zerafetim couture bordo ve gold etnik madalyon desenli esarp. Premium parca.", material: "%100 Ipek Couture Twill", size: "90x90 cm", color: "Kirmizi-Mavi-Gold", careInstructions: CARE_SILK },
  { id: 75, name: "Zerafetim Twill Esarp - Yesil Cicek Bahcesi", brand: "Zerafetim", price: 2399, oldPrice: 2800, image: p("esarp-034.jpeg"), category: "dokuma", isNew: true, description: "Zerafetim hardal-kahve cicek bahcesi desenli twill esarp.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Hardal-Kahve-Mavi", careInstructions: CARE_SILK },
  { id: 76, name: "Zerafetim Viskon Sal - Pudra Gul", brand: "Zerafetim", price: 849, image: p("esarp-037.jpeg"), category: "jersey", isNew: true, description: "Zerafetim viskon sal, pudra gul deseni. Hafif ve her mevsim.", material: "Viskon", size: "75x200 cm", color: "Pudra-Somon", careInstructions: CARE_COTTON },
  { id: 77, name: "Zerafetim Couture Esarp - Lacivert Osmanli", brand: "Zerafetim", price: 2599, image: p("esarp-032.jpeg"), category: "saten", description: "Zerafetim couture lacivert Osmanli motifli esarp. Turkuaz detaylarla gorkemli.", material: "%100 Ipek Couture Twill", size: "90x90 cm", color: "Lacivert-Turkuaz", careInstructions: CARE_SILK },
  { id: 78, name: "Zerafetim Twill Esarp - Turuncu Zincir", brand: "Zerafetim", price: 2240, image: p("esarp-026.jpeg"), category: "sifon", description: "Zerafetim turuncu zincir motifli twill esarp. Sicak tonlarda dinamik.", material: "%100 Ipek Twill", size: "90x90 cm", color: "Turuncu-Gri", careInstructions: CARE_SILK },
  { id: 79, name: "Zerafetim Yun Ipek Sal - Bordo Paisley", brand: "Zerafetim", price: 1749, oldPrice: 2200, image: p("esarp-027.jpeg"), category: "dokuma", isLimited: true, description: "Zerafetim bordo yun-ipek paisley sal. Sinirli uretim kis koleksiyonu.", material: "Yun-Ipek", size: "70x200 cm", color: "Bordo-Kirmizi", careInstructions: CARE_SILK },
  { id: 80, name: "Zerafetim Viskon Sal - Lacivert Puantiye", brand: "Zerafetim", price: 899, image: p("esarp-022.jpeg"), category: "jersey", description: "Zerafetim lacivert puantiye viskon sal. Is ve gunluk yasam icin pratik.", material: "Viskon", size: "75x200 cm", color: "Lacivert-Beyaz", careInstructions: CARE_COTTON },
];

export function getProductsByCategory(category: string): Product[] {
  return allProducts.filter((p) => p.category === category);
}

export function getNewProducts(): Product[] {
  return allProducts.filter((p) => p.isNew);
}

export function getLimitedProducts(): Product[] {
  return allProducts.filter((p) => p.isLimited);
}

export function getProductsByBrand(brand: string): Product[] {
  return allProducts.filter((p) => p.brand.toLowerCase() === brand.toLowerCase());
}

export function getProductById(id: number): Product | undefined {
  return allProducts.find((p) => p.id === id);
}

export function getSimilarProducts(product: Product, limit = 4): Product[] {
  return allProducts
    .filter((p) => p.id !== product.id && (p.category === product.category || p.brand === product.brand))
    .slice(0, limit);
}

export function handleWhatsAppOrder(product: Product) {
  const message = `Merhaba Kartal Esarp, ${product.brand} - ${product.name} (Kod: ${product.id}), ${product.price} TL fiyatindaki urunuzu siparis etmek istiyorum.`;
  return `https://wa.me/905XXXXXXXXX?text=${encodeURIComponent(message)}`;
}
